backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    files:
      - label: "All Articles"
        name: "articles"
        file: "articles.json"
        fields:
          - label: "Articles"
            name: "root"
            widget: "list"
            fields:
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Category", name: "category", widget: "select", options: ["Port Strategy", "Maritime Law", "Executive Dialogue", "Supply Chain", "Green Logistics
